[package]
name ="campher"
version ="0.0.1"
edition="2021"
author="Dessxvii anoncomrade993@gmail.com"

[dependencies]
rocket="0.5.0"
pixelate = {git="https://github.com/Anoncomrade993/pixelate"}
serde_json = ""
image = ""
chrono=""
base64 =""
